### PR TITLE
chore(test): add unit tests for 13 constants

### PR DESCRIPTION
**Pull request by drepram**
## Description

Wrote 4 unit tests to cover constants from URecoverySeedBox, USwitcher, UDropDownMenu, and UBottomSheet.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

PS: Should I use `chore(test)` or `feat(test)` for test-related commit messages?

### CODE REVIEW

**Comment by stavares843** [comment]
awesome, thanks @drepram 🎉 

`feat(test)` should work fine btw

**Review by stavares843 — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]
Tests working fine! 
image

**Comment by stavares843** [comment]
🎉

**Comment by lgmarchi** [comment]
> awesome, thanks @drepram 🎉
> 
> `feat(test)` should work fine btw

@stavares843 and @drepram, for this kind of commit we have test type to use as well, and in the scope we can put what we are testing. 

For example:
`test(Usizes): add unit tests for 13 constants`

For the PR title we have this allowed types to use:
image

**Pull request merged**
