### PR TITLE
chore(warp): Add warp-dart repo in uplink - UL-161 

### PR DESCRIPTION
**Pull request by lgmarchi**
#### We can access warp-dart as package now in Uplink
image

#### The path contains _../_, this means that it is backing the folder, so it starts in android folder inside Uplink, and after three of them, the path is in Satellite.im, so the next is just to access warp-dart, and do the path until jniLibs inside this repo
image

#### For demo purposes, warp was used in Profile pages, just to create an identity with username and message status, and the possibility to change them in Edit Profile page. This piece of code will be moved later.
https://user-images.githubusercontent.com/63157656/183503825-f1434ab0-8086-4580-ae82-576d99b8358f.mov

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] ✅ Build configuration change
- [x] 🗑️ Chore

### CODE REVIEW

**Review by tooshel — APPROVED** [review]
I noticed this includes the QR code stuff but you said you will fix it up. Approved!

**Comment by phillsatellite** [comment]
When Sara and I tested we both had issues with the profile page never loading. Tried on other apk's and was able load profile fine. Was this intended?
Captura_de_ecra_2022-08-09_as_19 00 07
Screen Shot 2022-08-09 at 2 11 35 PM

**Comment by phillsatellite** [comment]
Worked with Lucas a little on this yesterday, the issue was its missing the libs when github generates the apk so we are doing some research on how to insert those missing libs

**Comment by lgmarchi** [comment]
> Worked with Lucas a little on this yesterday, the issue was its missing the libs when github generates the apk so we are doing some research on how to insert those missing libs

For now the PR will be merged, but we are keeping the researchers to insert those libraries in apk generated by github actions.

**Pull request merged**
