### PR TITLE
update(Notifications): Update notifications widgets -  UL-135

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Update UNavDrawerWidget space 
image

### 2. Update notifications widgets, spaces and adjust their sizes
image
image
image

### 3. Add welcome notification when the user has no notification 
image

### 4. Add notifications in the UIShowRoom 
image

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧪 Tests
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hi Lucas! One little thing Sara and I were curious about, for the friend request notification the Decline button looks a little different on pr compared to figma but we weren't sure if it was just because on figma it was similar to the background color. Just wanted to double check 😂 
PR 
Screen Shot 2022-07-25 at 3 16 28 PM

Figma
Screen Shot 2022-07-25 at 3 45 27 PM

**Comment by lgmarchi** [comment]
> @phillsatellite 
Haha It is exactly because of this, if you go to Chats Session in Figma, you can see the button with other background color. 
https://www.figma.com/file/RMFzLQgD9RxmSR8Yp4pIqS/Android-MVP?node-id=4%3A9257
image

And if you notice, the text is a little bit decentralized, it is fixed in the other PR that Jenny was working as well.

**Comment by stavares843** [comment]
thanks for clarifying 🔨

**Review by phillsatellite — APPROVED** [review]

**Review by hyj1204 — APPROVED** [review]
Looks good. 

https://user-images.githubusercontent.com/14248245/181800885-67b3b28d-7c90-46b4-870b-0005269b8a8f.mov

**Pull request merged**
