### PR TITLE
feat(UserProfilePage): add home indicator(grey handler) on the top of user profile bottom sheet -UL-138

### PR DESCRIPTION
**Pull request by hyj1204**
## Description
Add home indicator(grey handler) on the top of user profile bottom sheet

https://user-images.githubusercontent.com/14248245/181079075-d2ff1d05-3795-4b93-8d60-538f96f3dcc3.mov

Please check this link for more detail of User profile page
https://deepspaceshipping.getoutline.com/share/6f8ef144-f8eb-4859-be28-e25f7f24edbf
## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by phillsatellite** [comment]
Works good! Only little thing I noticed was I can only view a persons profile if I am in the "blocked" list. Profile won't open if I try to view someone on my friends list. Is that intended? 

https://user-images.githubusercontent.com/93608357/181262224-3888a2fd-60db-4aac-9bb6-bf19390b6264.mov

**Comment by hyj1204** [comment]
> Works good! Only little thing I noticed was I can only view a persons profile if I am in the "blocked" list. Profile won't open if I try to view someone on my friends list. Is that intended?
> 

Yes, right now I implement the user profile page only in the blocked list as an entry point to test how the user profile will look like. Because some designs(like friend list animation in the bottom sheet , how friend list navigate back to user profile) of this page haven't fully confirmed, it will change in the future, so currently I just make one entry point as an example to test current design.   If you want test the user profile of different user's state, you can go to 'blocked_page.dart' and temporary change(do not commit) the `user ` property to see different user profile page base on different scenarios. 

image
Note:
`relationship: Relationship.block` means the user you are checking is blocked by you.
`isBlocked: true` means the user you are checking blocked you.

Here is the original PR which shows how the user profile will look like in different scenarios. 
https://github.com/Satellite-im/Uplink/pull/58

**Comment by stavares843** [comment]
thanks for clarifying 🔨

**Comment by phillsatellite** [comment]
Awesome, thank you!

**Review by phillsatellite — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]
UI is fine! 

image

**Pull request merged**
