### PR TITLE
test(ThemeType): refactor test

### PR DESCRIPTION
**Pull request by drepram**
## Description

Improve test in making it more readable for further development.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🧪 Tests
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2022-07-06, às 16 51 15

cc @drepram

**Comment by drepram** [comment]
Here I resolved another issue related to themes: 

image

image

By Lucas's instruction, I've modified the code in this branch too. Please take a look!

**Comment by stavares843** [comment]
🎉

**Review by lgmarchi — APPROVED** [review]
The way you have discovered to let the tests more legible are very good @drepram, congrats! 

image


image

**Pull request merged**
