### PR TITLE
add(ConstellationApi): Implement constellation for uploading the photo

### LINKED ISSUE #133: File: Implement constellation in uploading photo and FileIndexPage

### PR DESCRIPTION
**Pull request by hyj1204**
## Description
The current constellation is still not persist, which means after user close the app, the previous uploaded photos will disappear. @dariusc93 is working on it to make it persist in the future. 
This PR is to implement the current constellation for uploading the photo, check the photo list and preview the photo. Other features like favorite, rename, remove will be implemented in the PRs later. 
1. Implement constellation for uploading the photo, check the photo list and preview the photo.

https://user-images.githubusercontent.com/14248245/197580117-49e8436b-8187-475c-af72-60c0deb60e31.mov

2.Add ConstellationApi initial event in WarpBloc
image

3. Change the properties in Item since they can be null when uploading the photo.
`preview` is for PhotoDetailPage to preview the photo. 
image

4. Add `covertUTCStringToDateTime` function in `DateFormatUtils`
From constellation, we get a string like this from `getItemTimestamp()`and `getItemDateModification()`
`'2022-10-24 13:47:53.997047236 UTC'`
By using 
```
DateFormatUtils.covertUTCStringToDateTime(
      getItemTimestamp(),
    );
```
we will get a `DateTime` value used in Item class.

5. More detail about constellation and how I struct the code
https://satellite.wiki/s/e2f1d3d2-6067-448c-8d6e-b6c264bb9acb

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🧹 Code refactor

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hi Yijing! I tried testing and was having some issues so I asked Sara to test as well and she experienced same problem, when you would take photo or select photo to upload you would get this message (we should also change this to "Could not load the files"

image

if the user exits the app then returns back this message would appear and file still would not upload 

image

**Comment by hyj1204** [comment]
@phillsatellite 
I changed the error text here. The upload feature should be fine now since Darius updated the warp-dart. Let me know if you got some error again.
image
For the second issue, currently the constellation is not persist(so the file will disappear after closing the app) @dariusc93 is still working on it.

**Comment by hyj1204** [comment]
@phillsatellite 
I just noticed Darius updated the code to make constellation persist, I am gonna update it.

**Comment by phillsatellite** [comment]
Hi Yijing! Thanks for the update and this is working a lot better! 🎉  The only minor thing I thought I had mentioned but totally forgot to include it was the error message here should be in English, but other than that PR is great!!! 😄 

image

**Review by lgmarchi — APPROVED** [review]
PR Approved. 

1. We don't have all functions already from constellation 
2. Mock file to test is yet in the app, to be used if necessary 
3. Warp Constellation was added in Uplink.

**Review by phillsatellite — APPROVED** [review]

**Comment by hyj1204** [comment]
The text in the NoItemPage will be changed in the next PR

**Pull request merged**
