### PR TITLE
add(file): add PhotoDetailPage, FavoritesListPage, RemoveListPage and showFileOptionsBottomSheet

### LINKED ISSUE #115: File: Add UI for Files page
File UI note:
https://satellite.wiki/s/05435d28-69d1-43a1-bdd1-3ba82347bced

Migrated from: https://satellite-im.atlassian.net/browse/UL-189

### PR DESCRIPTION
**Pull request by hyj1204**
Test tip: You need to upload at least one photo to test all the features. If you want to test multiple photos in a quick way, you can uncomment the code in `MockFileApi` like this. It will generate 10 fake files after you upload photo once. 
Do not commit any code of it since it is just for testing. 
image
## Description
1. Add `PhotoDetailPage` to preview photo and to do favorite, rename and remove action on it. 
By tapping the grid view item or tapping the list tile to navigator to the `PhotoDetailPage`. 

https://user-images.githubusercontent.com/14248245/195143022-341599a4-65f1-47f7-aaf3-88f217d726f2.mp4

2. Add `FileOptionsBottomSheet`
By long pressing the grid view item or tapping the list tile will evoke the `FileOptionsBottomSheet`

https://user-images.githubusercontent.com/14248245/195143546-e4a29e7d-b304-4859-a420-6adaa02ef1ba.mp4

3. Favorite item
By tapping the 'Favorite' option in `FileOptionsBottomSheet`, or heart icon in PhotoDetailPage, user favorite the item. 
A favorited item
 - It will show heart icon in grid view
 - Its more option sheet will show 'Favorited' with CTABlue color
 - It will show in the `FavoritesListPage`
 
https://user-images.githubusercontent.com/14248245/195144751-01e16bf6-1c7f-4ba6-864f-0435db0eefd9.mov

4. Rename item
By tapping the 'Rename' option in `FileOptionsBottomSheet`, or pencil icon in PhotoDetailPage, user can rename the item.

https://user-images.githubusercontent.com/14248245/195145360-0be023de-e527-4d37-8885-424af11783c4.mov

5. Remove single item 
By tapping the 'Remove' option in `FileOptionsBottomSheet`, or trash bin icon in PhotoDetailPage, user can remove that item.

https://user-images.githubusercontent.com/14248245/195145827-ab1c1931-ffbf-4c7d-9774-d42ebd58cc0f.mov

6. Remove multiple items
In `RemoveListPage`, user can select one or multiple items to remove. 
`RemoveListPage` can be access through the hamburger menu icon in the Appbar of the `FileIndexPage` or `FavoritesListPage `

[Click here](https://satellite.wiki/s/264c801a-2e64-4527-8fd6-af73baa67540) for more detail about how I structure the code. 

Through `FileIndexPage`

https://user-images.githubusercontent.com/14248245/195146517-7c5d86e6-6d63-4209-9e30-ab4d9f865027.mov

Through `FavoritesListPage `

https://user-images.githubusercontent.com/14248245/195148533-34d8fcd1-61d9-4f7a-9bb4-d34f6256f95f.mov

7. Add naming  restriction
All remove features are base on the name of item, which  means a name cannot be used in multiple items, otherwise, they will be remove together. So I added naming  restriction to prevent name/rename an item with exist name. 

After click 'check' floating button, it will check if this name has been used, if so, it will show an error message. 

In the renaming case, if use didn't change the name(the same name as previous one), it will back to previous page, instead of showing the bottom sheet to change the name. 

In naming case(upload item)

https://user-images.githubusercontent.com/14248245/195388437-9d12ba4b-3d8f-4337-8a41-0757760c572b.mov

In renaming case

https://user-images.githubusercontent.com/14248245/195388517-f773abef-99ba-4f5a-9ce4-21e62582e33f.mov

8. Refactor all the pages with routeName used in Navigator(Auth and File section)

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
Just a few things I found while testing, it looks like if the user taps the list/grid button repeatedly it will look a little glitchy 

Another thing I noticed, User can name all the files the same name. When they do that and they want to delete one of them it will delete all the files with that same name 

Other than that this is a really awesome feature! Thanks Yijing! 🎉 

https://user-images.githubusercontent.com/93608357/195167656-1d4de549-3e24-4a1e-ab63-5533f01c1162.mp4

**Comment by hyj1204** [comment]
@phillsatellite 
Thanks for catching up these issues. 
I made some changes to fix the glitchy when repeatedly taping the layout button. 
I also added the naming restriction on `NameFilePage` to make sure user cannot give the same name to different items.
You can test it again and let me know if any issue is still there.

**Comment by phillsatellite** [comment]
Hi @hyj1204  All the fixes you added work amazing! Thank you! When I went through to test again I found one very very small thing, when the user is selecting which file they want to delete it looks like there is an unintended animation happening around the corner of selected file, attached screen recording below. Other than this small little ui issue this pr is perfect! ✨ 

https://user-images.githubusercontent.com/93608357/195411760-72894304-4e8a-42cd-a350-c0ec42e032c8.mp4

**Comment by hyj1204** [comment]
@phillsatellite 
Thanks for spotting it. I just made new commit to remove the default splash color, and that flash around corner is away now.  You can test it again.

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
@hyj1204  Everything on it is perfect! Approved 🎉

**Review by lgmarchi — APPROVED** [review]
This PR is a good advance on Files section. 

Now we can favorite and remove pictures uploaded. 

image

image

image

**Pull request merged**
